feat: modulo3
adrianopratesr/software-engineering pull request #1
Opened 2023-08-29 02:45 UTC by adrianopratesr

Este PR adiciona os exercicios do módulo 3

2023-08-29 02:52 UTC, luanarahal commented on software-engineer-I/fc-1/javascript/modulo-3/ex-1.js
> +  return (base * height) / 2;
declarar a variável 
```javascript
const area = (base * height)/2;
return area;
```

2023-08-29 02:52 UTC, luanarahal commented on software-engineer-I/fc-1/javascript/modulo-3/ex-1.js
> +const calculateArea = (base, height) => {
calculateTriangleArea

2023-08-29 02:55 UTC, adrianopratesr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-1.js
> +  return (base * height) / 2;
obrigado pelo codigo pronto

2023-08-29 02:55 UTC, luanarahal commented on software-engineer-I/fc-1/javascript/modulo-3/ex-1.js
> +  return (base * height) / 2;
🖕

2023-08-29 02:57 UTC, adrianopratesr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-1.js
> +  return (base * height) / 2;
Feito amor da minha vida

2023-08-29 02:57 UTC, adrianopratesr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-1.js
> +const calculateArea = (base, height) => {
Feito

2023-08-29 02:58 UTC, luanarahal commented on software-engineer-I/fc-1/javascript/modulo-3/ex-1.js
> +console.log(calculateTriangleArea(base, height));
faltou um enter

2023-08-29 03:00 UTC, adrianopratesr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-1.js
> +console.log(calculateTriangleArea(base, height));
vait er block

2023-08-29 03:01 UTC, luanarahal commented on software-engineer-I/fc-1/javascript/modulo-3/ex-1.js
> +console.log(calculateTriangleArea(base, height));
que língua é essa?

2023-08-29 03:02 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-1.js
> +console.log(calculateTriangleArea(base, height));
https://media.giphy.com/media/f9GigOIfDCwJuboMkq/giphy-downsized-large.gif

2023-08-29 03:02 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-1.js
> +console.log(calculateTriangleArea(base, height));
https://media.giphy.com/media/f9GigOIfDCwJuboMkq/giphy-downsized-large.gif

2023-08-29 03:28 UTC, luanarahal commented on ex-3.js
> +const compareAge = (age1, age2) => {
compareAges

2023-08-29 03:28 UTC, luanarahal commented on software-engineer-I/fc-1/javascript/modulo-3/ex-3.js
> +console.log(compareAge(age1, age2));
compareAges

2023-08-30 14:10 UTC, antoniomatiolijr requested changes

2023-08-30 14:10 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-10.js
> +const burden1 = 1;
weight

2023-08-30 14:10 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-11.js
> +const sale = 10;
discountRate

2023-08-30 14:10 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-11.js
> +const calculateSaleAndTax = (price, sale, tax) => {
calculateDiscountAndTax

2023-08-30 14:10 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-11.js
> +  return price - valueSale + valueTax;
`return (price - discountValue) + taxValue`

tira do preço e soma a taxa

2023-08-30 14:10 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-12.js
> +};
`2 * (length + width)`

2023-08-30 14:10 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-5.js
> +const validateAgeVote = (age) => {
isEligibleToVote

2023-08-30 14:10 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-7.js
> +const blueSky = false;
isBlueSky, isNiceWeather, isWindy

2023-08-30 14:10 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-8.js
> +const percentageSalaryIncrease = (salary, increase) => {
calculateSalaryIncrease

2023-08-30 14:10 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-9.js
> +  return (points -= 5);
```typescript
points += bonus;
points -= 5;
return points
```

2023-08-30 14:10 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-9.js
> +const totalGamePoints = (points, bonus) => {
calculateGamePoints

2023-08-30 14:10 UTC, antoniomatiolijr reviewed
Vou deixar passar que faltou o commit do exercício 3

2023-08-30 14:30 UTC, luanarahal commented on software-engineer-I/fc-1/javascript/modulo-3/ex-7.js
> +    return "É um bom dia para piquinique";
piquenique

2023-08-30 14:30 UTC, luanarahal commented on software-engineer-I/fc-1/javascript/modulo-3/ex-7.js
> +    return "Não é um bom dia para piquinique";
piquenique

2023-08-30 14:52 UTC, luanarahal approved these changes

2023-08-30 16:20 UTC, antoniomatiolijr requested changes

2023-08-30 16:20 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-11.js
> +  return price - discountValue + taxValue;
`return (price - discountValue) + taxValue;`

2023-08-30 16:20 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-11.js
> +  return price - discountValue + taxValue;
só para ficar mais claro visualmente

2023-08-30 16:20 UTC, antoniomatiolijr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-7.js
> +  if ((isNiceWeather && isBlueSky) || !isWind) {
`(isNiceWeather && isBlueSky) && !isWind`

caso esteja `(true && true) || true` => vai dar `true`, ou seja vc vai sair para um piquinique na ventania então troquei o `||` por `&&`

2023-08-30 16:31 UTC, adrianopratesr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-7.js
> +  if ((isNiceWeather && isBlueSky) || !isWind) {
Achei que era um vento de boas kkkkkkkkkkkk
Um ceu azul em um dia super quente e bom um ventinho kkkkkkk

2023-08-30 16:37 UTC, adrianopratesr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-7.js
> +  if ((isNiceWeather && isBlueSky) || !isWind) {
Done

2023-08-30 16:37 UTC, adrianopratesr commented on software-engineer-I/fc-1/javascript/modulo-3/ex-11.js
> +  return price - discountValue + taxValue;
done

2023-08-31 22:52 UTC, antoniomatiolijr approved these changes

2023-08-31 22:52 UTC, merged