javascript -> módulo 3 -> tópico 2
adrianopratesr/software-engineering pull request #11
Opened 2023-12-14 14:59 UTC by adrianopratesr

2023-12-14 16:38 UTC, antoniomatiolijr reviewed
indo bem!

2023-12-14 18:00 UTC, antoniomatiolijr requested changes

2023-12-14 18:00 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-3.js
> +console.log(higherNumber([2, 3, 1000]));
```javascript

const max = (...numbers) => {
return Math.max(...numbers)
};

const currentNumbers = [1, 2, 3, 4];
const maxNumber = max(...currentNumbers);
```

2023-12-15 01:15 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-3.js
> +console.log(higherNumber([2, 3, 1000]));
feito

2023-12-15 11:59 UTC, antoniomatiolijr requested changes

2023-12-15 11:59 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-4.js
> +  for (const a in object) {
`const prop` representa melhor

2023-12-15 11:59 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-4.js
> +const printddress = (object) => {
printAddress

2023-12-15 11:59 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-6.js
> +const gradeAdriano = 10;
const adrianoGrade = 10;

2023-12-15 11:59 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-6.js
> +  grade <= 5 ? console.log("Aluno aprovado") : console.log("Aluno reprovado");
A ordem ta errada, se a nota for <= 5 vai aparecer aprovado

2023-12-15 11:59 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-7.js
> +  });
da um return e depois usa console log, o objetivo dessa função é ser uma fabrica de objetos e não para printar

2023-12-15 19:10 UTC, antoniomatiolijr requested changes

2023-12-15 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-11.js
> +  return students.filter((student) => student.age > age);
passa students tb como parametro

2023-12-15 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-11.js
> +  return students.filter((student) => student.age > age);
pois vc ta acessando o array de forma global

2023-12-15 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-12.js
> +function averageAge() {
students como parametro

2023-12-15 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-13.js
> +    0
o inicial aqui n é 0 e sim {}, pois vc ta retornando o student

2023-12-15 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-13.js
> +function youngestStudent() {
students como parametro

2023-12-15 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-14.js
> +function alphabeticalOrder() {
students como parametro

2023-12-15 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-15.js
> +    return ageInYears;
isola essa parte na função e o map pode ser feito por fora

2023-12-15 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-16.js
> +  return agrupador;
isso não agrupa o resultado e sim transforma ele.

Deveria ser: 

{
"0-12": [students],
"12-18": [students],
...
}

2023-12-15 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-9.js
> +  } else if (typeof base !== "number" || typeof height !== "number") {
usa só if

2023-12-15 19:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-9.js
> +    return console.log(`A área do retangulo é: ${base * height}`);
ai não precisa do else

2023-12-15 20:15 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-4.js
> +const printddress = (object) => {
Feito

2023-12-15 20:15 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-4.js
> +  for (const a in object) {
Feito

2023-12-15 20:15 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-6.js
> +  grade <= 5 ? console.log("Aluno aprovado") : console.log("Aluno reprovado");
Feito

2023-12-15 20:15 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-6.js
> +const gradeAdriano = 10;
Feito

2023-12-15 20:15 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-7.js
> +  });
feito

2023-12-15 20:18 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-11.js
> +  return students.filter((student) => student.age > age);
Feito

2023-12-15 20:19 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-12.js
> +function averageAge() {
Feito

2023-12-15 20:19 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-13.js
> +    0
Feito

2023-12-15 20:20 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-13.js
> +function youngestStudent() {
Feito

2023-12-15 20:20 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-14.js
> +function alphabeticalOrder() {
feito

2023-12-15 20:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-9.js
> +  } else if (typeof base !== "number" || typeof height !== "number") {
Feito

2023-12-15 20:24 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-9.js
> +    return console.log(`A área do retangulo é: ${base * height}`);
Feito

2023-12-16 03:10 UTC, antoniomatiolijr requested changes

2023-12-16 03:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-17.js
> +const findStudentsByName = (string) => {
Muda string para name

2023-12-16 03:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-18.js
> +    return getmes === mesdoaniversario;
Isso também tem que estar em uma outra função 

A talvez seja melhor ao invés de passar número 5, passar o mês fica mais legível para entender e depois você converte o mês em número através de um objeto com de para

2023-12-16 03:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-20.js
> +const removerestudante = (name) => {
removeStudentByName

2023-12-16 03:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-21.js
> +const convertDate = (students) => {
Essa função pode ser só a parte da conversão da data o map pode estar fora de uma função

2023-12-16 03:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-6.js
> +  grade <= 5 ? console.log("Aluno reprvado") : console.log("Aluno aprovado");
"Aluno reprovado"

Outro ponto retorna so a string a função não é responsável por printar o resultado

2023-12-16 03:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-9.js
> +    return console.log(
Sem o console log

2023-12-16 03:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-9.js
> +  return console.log(`A área do retangulo é: ${base * height}`);
Sem o console log

2023-12-16 03:17 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-20.js
> +const removerestudante = (name) => {
feito

2023-12-16 03:19 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-17.js
> +const findStudentsByName = (string) => {
Feito

2023-12-16 14:10 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-16.js
> +  const grouper = students.map((student) => {
Waiting

2023-12-17 03:13 UTC, antoniomatiolijr requested changes

2023-12-17 03:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-6.js
> +  grade <= 5 ? "Aluno reprvado" : "Aluno aprovado";
"Aluno reprovado"

2023-12-17 03:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-17.js
> +const findStudentsByName = (name) => {
students como parâmetro

2023-12-17 03:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-18.js
> +const aniversariantedomes = (students, mesdoaniversario) =>
Pt br?

2023-12-17 03:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-20.js
> +const removeStudentByName = (name) => {
Passar students pra função

2023-12-17 07:11 UTC, antoniomatiolijr requested changes

2023-12-17 07:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-27.js
> +console.log(findStudent(students, 3));
Converte para ao invés de passar número passar o mês por escrito isso deixa mais claro o objetivo do código

2023-12-17 07:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-29.js
> +    )} dias`;
Os dois returns são praticamente iguais só mudando as variáveis transforma em uma função que faz essa msg e você vai ver o código ficar bem mais limpo

2023-12-17 07:11 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-30.js
> +const filteringStudentAges = (students, age1, age2) => {
Coloca nomes mais representativos para age1 e age2 algo como startAge e endAge isso deixa muito mais claro para que serve aquele parâmetro

2023-12-17 15:58 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-21.js
> +const convertDate = (students) => {
Feito

2023-12-17 15:58 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-6.js
> +  grade <= 5 ? console.log("Aluno reprvado") : console.log("Aluno aprovado");
Feito

2023-12-17 15:58 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-9.js
> +    return console.log(
Feito

2023-12-17 15:59 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-9.js
> +  return console.log(`A área do retangulo é: ${base * height}`);
Feito

2023-12-17 15:59 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-16.js
> +  const grouper = students.map((student) => {
feito

2023-12-17 15:59 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-6.js
> +  grade <= 5 ? "Aluno reprvado" : "Aluno aprovado";
feito

2023-12-17 16:00 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-18.js
> +const aniversariantedomes = (students, mesdoaniversario) =>
Feito

2023-12-17 16:03 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-30.js
> +const filteringStudentAges = (students, age1, age2) => {
Feito

2023-12-17 16:05 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-20.js
> +const removeStudentByName = (name) => {
Feito

2023-12-17 16:05 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-17.js
> +const findStudentsByName = (name) => {
Feito

2023-12-21 05:18 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-18.js
> +    return getmes === mesdoaniversario;
Feito

2023-12-21 05:18 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-27.js
> +console.log(findStudent(students, 3));
Feito

2023-12-21 05:18 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-15.js
> +    return ageInYears;
Feito

2023-12-21 05:18 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-29.js
> +    )} dias`;
Feito

2023-12-21 19:37 UTC, antoniomatiolijr requested changes

2023-12-21 19:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-15.js
> +  return Math.round(ageInYears);
a Lu tinha visto que é melhor usar Math.floor

2023-12-21 19:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +console.log(calculateAge(students));
melhor colocar em um forEach assim vc não perde as outras propriedades

2023-12-21 19:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-27.js
> +  };
percebi que essa função se repete entre os arquivos consegue criar um `utils.date.js`

2023-12-21 19:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-28.js
> +  const filterStudentsMettingMonthBirth = students.filter((student) =>
studentsBornedInSpecificMonth

2023-12-21 19:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-30.js
> +      return `Os estudentes que tem idade entre ${initialAge} e ${endAge} são ${student.name}`;
return student, não é responsabilidade dessa função apresentar os dados.

2023-12-21 19:37 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-29.js
> +  return printMessage(student1, student2, diference2);
não precisa fazer isso é só fazer um - o outro e o resultado vc da um Math.abs ou seja volta o valor positivo

2023-12-24 17:10 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-15.js
> +  return Math.round(ageInYears);
Feito

2023-12-24 17:10 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +console.log(calculateAge(students));
refeito o exercicio

2023-12-24 17:11 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-28.js
> +  const filterStudentsMettingMonthBirth = students.filter((student) =>
feito

2023-12-24 17:12 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-30.js
> +      return `Os estudentes que tem idade entre ${initialAge} e ${endAge} são ${student.name}`;
feito

2023-12-24 17:14 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-29.js
> +  return printMessage(student1, student2, diference2);
Feito

2023-12-24 17:17 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-27.js
> +  };
Feito

2023-12-24 17:45 UTC, antoniomatiolijr requested changes

2023-12-24 17:45 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-15.js
> +  const ageInYears = millisecondsDifference / 1000 / 60 / 60 / 24 / 365;
isso pode ser outra função

2023-12-24 17:45 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +  const ageInYears = millisecondsDifference / 1000 / 60 / 60 / 24 / 365;
mesma coisa do outro

2023-12-24 17:45 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +  }else {
prettier morreu né

2023-12-24 17:45 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +const filterConsumption = (studentId, purchases) =>{
só o nome como falei

2023-12-24 17:45 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +    const correlacionando = filterConsumption(student.id, purchases);
correlacionando?

2023-12-24 17:45 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-27.js
> +function getMonthNumber(monthName) {
essa função ja apareceu em vários lugares o que acha de criar um utils

2023-12-24 17:45 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-29.js
> +const convertingMillisecondInDays = (milliseconds) => {
varios lugares usam essa

2023-12-24 18:05 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +  }else {
sim kkkkk

2023-12-24 18:06 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +    const correlacionando = filterConsumption(student.id, purchases);
feito

2023-12-24 18:07 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-27.js
> +function getMonthNumber(monthName) {
feito

2023-12-24 18:08 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-29.js
> +const convertingMillisecondInDays = (milliseconds) => {
feito

2023-12-24 18:08 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +const filterConsumption = (studentId, purchases) =>{
feito

2023-12-24 18:09 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-15.js
> +  const ageInYears = millisecondsDifference / 1000 / 60 / 60 / 24 / 365;
feito

2023-12-24 18:09 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +  const ageInYears = millisecondsDifference / 1000 / 60 / 60 / 24 / 365;
feito

2023-12-24 19:51 UTC, antoniomatiolijr requested changes

2023-12-24 19:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +  return purchases.filter((purchase) => purchase.idEstudante === studentId);
Ah tem uma coisa a mais que da pra fazer aqui é tirar o id do estudante com um map pois no exercício pede as compras por range ou seja trazer o id do estudante é errado a Luana manja caso precise de apoio

2023-12-24 19:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-29.js
> +const printMessage = (student1, student2, diference) => {
Essa função deveria ser só responsável por printar ou seja 

Vc deveria passar os nomes dos students direto e já convertido a diferença

2023-12-24 19:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-30.js
> +    if (student.age >= initialAge && student.age <= endAge) {
Faz assim return no lugar do if( assim vc retorna a condição direta fica mais simples

2023-12-24 19:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/utils.date.js
> +
Meow

2023-12-25 17:38 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/utils.date.js
> +
Feitoo

2023-12-25 17:39 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-30.js
> +    if (student.age >= initialAge && student.age <= endAge) {
Feito

2023-12-25 17:42 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-29.js
> +const printMessage = (student1, student2, diference) => {
Feito

2023-12-25 17:52 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +  return purchases.filter((purchase) => purchase.idEstudante === studentId);
feito

2023-12-26 12:20 UTC, antoniomatiolijr requested changes

2023-12-26 12:20 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-18.js
> +const checkMonthOfBirthday = (date, bithdayMonth) => {
isMonthTheSame e pode ir para o utils.

2023-12-26 12:20 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +const rangeAgeStudents = (age) => {
getAgeRange

2023-12-26 12:20 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +    const correlating = filterPurchasesByStudent(student.id, purchases);
uma dica que eu dei para a luh foi, como nomear uma variavel que vem de um resultado de uma função é só tirar o verbo `filter` dai vira `const purchasesByStudent = filterPurchasesByStudent(student.id, purchases);`

2023-12-26 12:20 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-29.js
> +  const diference = Math.abs(dateOfBirthStudent1 - dateOfBirthStudent2);
difference

2023-12-26 12:20 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-30.js
> +
mata esse espaço a mais

2023-12-26 12:20 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-30.js
> +
remove aqui

2023-12-26 12:20 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/utils.date.js
> +export const isMonthTheSame = (date, monthNumber) => {
da para usar na outra função que eu comentei.

2023-12-26 12:20 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/utils.date.js
> +
num resolveu ainda rs

2023-12-26 12:20 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/utils.date.js
> +    return Math.floor(ageInYears);
da para usar a que converte aqui

2023-12-26 12:20 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/utils.date.js
> +    return Math.round(milliseconds / 1000 / 60 / 60 / 24);
troca o `round` por `floor`

2023-12-30 03:53 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-18.js
> +const checkMonthOfBirthday = (date, bithdayMonth) => {
feito

2023-12-30 03:54 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +const rangeAgeStudents = (age) => {
feito

2023-12-30 03:54 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-29.js
> +  const diference = Math.abs(dateOfBirthStudent1 - dateOfBirthStudent2);
feito

2023-12-30 03:55 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-30.js
> +
feito

2023-12-30 03:55 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-30.js
> +
feito

2023-12-30 03:57 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/utils.date.js
> +
feito

2023-12-30 03:58 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/utils.date.js
> +    return Math.floor(ageInYears);
feito

2023-12-30 03:58 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/utils.date.js
> +    return Math.round(milliseconds / 1000 / 60 / 60 / 24);
feito

2023-12-30 04:00 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-22.js
> +    const correlating = filterPurchasesByStudent(student.id, purchases);
feito

2023-12-30 04:01 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/utils.date.js
> +export const isMonthTheSame = (date, monthNumber) => {
nao entendi mano

2023-12-30 23:15 UTC, antoniomatiolijr requested changes

2023-12-30 23:15 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-18.js
> +  return month === bithdayMonth;
isMonthTheSame do utils

2023-12-30 23:15 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/ex-4.js
> +
remover linhas

2023-12-30 23:15 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/ex-4.js
> +}catch (error){
} catch

2023-12-30 23:15 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/ex-4.js
> +}
provavelmente espaço

2023-12-30 23:15 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-2.js
> +    if(number1 < 0 || number2 < 0){
`<=`

2023-12-30 23:15 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-2.js
> +        throw new Error("Só é aceito positivos");
"Somente é aceito números positivos"

2023-12-30 23:15 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-3.js
> +    return "E-mail inserido corretamente"
true

2023-12-30 23:15 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-3.js
> +}
provavelmente é espaço

2023-12-30 23:30 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-3/topico-2/ex-18.js
> +  return month === bithdayMonth;
feito

2023-12-30 23:31 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-4/ex-4.js
> +
Feito

2023-12-30 23:31 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-4/ex-4.js
> +}catch (error){
vou corrigir no outro pr

2023-12-30 23:31 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-2.js
> +    if(number1 < 0 || number2 < 0){
vou corrigir no outro

2023-12-30 23:32 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-4/ex-4.js
> +}
mesma coisa

2023-12-30 23:32 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-2.js
> +        throw new Error("Só é aceito positivos");
mesma coisa

2023-12-30 23:32 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-3.js
> +    return "E-mail inserido corretamente"
mesma coisa

2023-12-30 23:32 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-4/topico-1/ex-3.js
> +}
mesma coisa

2023-12-30 23:47 UTC, antoniomatiolijr approved these changes

2023-12-30 23:47 UTC, merged