feat: ex-1
adrianopratesr/software-engineering pull request #13
Opened 2024-01-09 01:11 UTC by adrianopratesr

Add exercise promisses

2024-01-13 18:49 UTC, antoniomatiolijr requested changes

2024-01-13 18:49 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-1.js
> +
tem que dar um jeito nesse formatador

2024-01-14 16:53 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-1.js
> +
Arrumado kkk

2024-01-15 15:39 UTC, antoniomatiolijr requested changes

2024-01-15 15:39 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-10.js
> +  .then((reuslt) => console.log(reuslt))
result ta escrito errado

2024-01-15 15:39 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-3.js
> +          hoursePower: 490,
horsePower

2024-01-15 15:39 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-6.js
> +  .then((reusltJson) => console.log(reusltJson))
👀

2024-01-15 15:39 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-9.js
> +    setTimeout(() => resolve("cinco segundos"), 5000);
muda para dois segundos e ve o que acontece kkkk, tem um erro na implementação, fala com a @luanarahal

2024-01-15 16:37 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-10.js
> +  .then((reuslt) => console.log(reuslt))
Feito

2024-01-15 16:38 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-3.js
> +          hoursePower: 490,
Feito

2024-01-15 16:38 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-6.js
> +  .then((reusltJson) => console.log(reusltJson))
Feito

2024-01-15 18:56 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-9.js
> +    setTimeout(() => resolve("cinco segundos"), 5000);
feito

2024-01-15 19:34 UTC, antoniomatiolijr requested changes

2024-01-15 19:34 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-5.js
> +  .then((reusltJson) => console.log(reusltJson));
result ta escrito errado

2024-01-15 19:34 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-6.js
> +  .then((resultJson) => console.log(resultJson))
pode chamar só de `data` normalmente usamos isso ou `json`

2024-01-15 19:55 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-6.js
> +  .then((resultJson) => console.log(resultJson))
done

2024-01-15 19:58 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-5.js
> +  .then((reusltJson) => console.log(reusltJson));
feito

2024-01-15 20:30 UTC, antoniomatiolijr requested changes

2024-01-15 20:30 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-5.js
> +  .then((reusltJson) => console.log(reusltJson));
👀

2024-01-15 20:36 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-2/ex-5.js
> +  .then((reusltJson) => console.log(reusltJson));
Feito

2024-01-15 20:44 UTC, antoniomatiolijr approved these changes

2024-01-15 20:44 UTC, merged