Feat/se1 fc1 js modulo5 topico3
adrianopratesr/software-engineering pull request #15
Opened 2024-01-26 20:33 UTC by adrianopratesr

Adicionando execicios modulo5 topico3

2024-01-27 22:05 UTC, antoniomatiolijr requested changes

2024-01-27 22:05 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-3/ex-5.js
> +  const findData = await fetch("https://randomuser.me/api/");
o nome da variável deveria refletir o que ela retorna

2024-01-27 22:05 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-3/ex-6.js
> +    const findData = await fetch("https://randomuser.me/api/");
same as above

2024-01-27 22:05 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-3/ex-9.js
> +      .catch((err) => console.error(err));
async/await

2024-02-05 01:30 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-3/ex-5.js
> +  const findData = await fetch("https://randomuser.me/api/");
Feito

2024-02-05 01:31 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-3/ex-6.js
> +    const findData = await fetch("https://randomuser.me/api/");
Feito

2024-02-05 01:41 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-5/topico-3/ex-9.js
> +      .catch((err) => console.error(err));
Feito

2024-02-05 12:46 UTC, antoniomatiolijr approved these changes

2024-02-05 12:47 UTC, merged