feat: add ex1
adrianopratesr/software-engineering pull request #16
Opened 2024-01-27 20:04 UTC by adrianopratesr

Add modulo 6 topico 2

2024-01-27 22:23 UTC, antoniomatiolijr requested changes

2024-01-27 22:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +    const create = await fetch(url, {
lembra vc deve deixar claro o que foi retornado

2024-01-27 22:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-2.js
> +      },
isso aqui aparece em todas as funções concorda que pode ser uma função que recebe o httpMethod e o contentType? e vc reuzar ela?

2024-01-27 22:23 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-4.js
> +    const create = await fetch(url, {
isso é update?

2024-02-05 01:48 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +    const create = await fetch(url, {
Feito

2024-02-05 01:59 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-2.js
> +      },
Feito

2024-02-05 01:59 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-4.js
> +    const create = await fetch(url, {
Feito

2024-02-05 12:46 UTC, antoniomatiolijr requested changes

2024-02-05 12:46 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +const url = "http://localhost:3000/client";
`CLIENT_URL`

2024-02-05 12:46 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/utills.https.js
> +};
da para fazer em uma função só.

e o nome dela deveria ser mais claro algo como makeHttpRequest

2024-02-05 12:46 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-2.js
> +const url = "http://localhost:3000/client";
mesma coisa

2024-02-05 12:46 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-3.js
> +import { httpResponseJsonData } from "./utills.https";
utillllllls? e coloca http no nome.

2024-02-05 12:46 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/utills.https.js
> +  await fetch(url, {
Outra coisa a função só constrói o miolo e não executa o fetch.

2024-02-05 12:46 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-3.js
> +    const response = await clientUpdateResponse.text();
.text()? n deveria ser .json()?

2024-02-05 12:46 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-4.js
> +const url = "http://localhost:3000/client/9c0118ce-0da6-4c6f-b01f-290a02d2d287";
nunca passar o id direto na URL, separa em outra variável

2024-02-05 12:46 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-7.js
> +const makeUrlPokeApi = (namePokemon) => {
igual exercício anterior `pokemonName` ingles é sempre ao contrário

2024-02-06 14:57 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-3.js
> +    const response = await clientUpdateResponse.text();
o retorno da Api que o Gabriel contruiu é do tipo texto

2024-02-07 21:01 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-1.js
> +const url = "http://localhost:3000/client";
Doni

2024-02-07 21:02 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/utills.https.js
> +};
Doni

2024-02-07 21:02 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-3.js
> +import { httpResponseJsonData } from "./utills.https";
doni

2024-02-07 21:07 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-4.js
> +const url = "http://localhost:3000/client/9c0118ce-0da6-4c6f-b01f-290a02d2d287";
doni

2024-02-07 21:08 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-7.js
> +const makeUrlPokeApi = (namePokemon) => {
doni

2024-02-07 21:08 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-2.js
> +const url = "http://localhost:3000/client";
doni

2024-02-07 21:16 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/utills.https.js
> +  await fetch(url, {
doni

2024-02-08 03:22 UTC, antoniomatiolijr requested changes

2024-02-08 03:22 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/utils.http.js
> +};
o melhor é a função retornar um httpRequest e se chamar httpResponse

2024-02-08 03:22 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/utils.http.js
> +export const makeHttpResponse = async (method) => {
pq n é uma função só?

2024-02-09 13:57 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/ex-3.js
> +    const response = await clientUpdateResponse.text();
aceito ser feito em outro PR

2024-02-09 13:57 UTC, antoniomatiolijr requested changes

2024-02-09 13:57 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-6/topico-2/utils.http.js
> +export const makeHttpRequest = async (
é async pq?

2024-02-11 11:43 UTC, antoniomatiolijr approved these changes

2024-02-11 11:43 UTC, merged