feat: add execises
adrianopratesr/software-engineering pull request #17
Opened 2024-02-12 00:13 UTC by adrianopratesr

Add module 7 topic 1

2024-02-12 02:52 UTC, antoniomatiolijr requested changes

2024-02-12 02:52 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const paragraph = document.getElementsByTagName("p");
seria no plural pois não é só um parágrafo e sim vários

2024-02-12 02:52 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const alterClass = document.getElementsByClassName("destaque");
O que alterclass tem haver com o que está sendo buscado? Aqui não é uma função e sim uma variável logo ela deveria representar o que ela armazena que é um conjunto de destaques

2024-02-12 02:52 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const elementClass = document.querySelector(".item");
Mesma coisa

2024-02-12 02:52 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const buttonText = document.getElementById("botaoClique");
Mesma coisa

2024-02-12 02:52 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const alterColorList = document.querySelectorAll("li.item");
Mesma coisa

2024-02-12 02:52 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const alterClassContent = document.getElementsByClassName("destaque");
Mesma coisa

2024-02-12 02:52 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const alterFontText = document.getElementsByTagName("span")[0];
Mesma coisa

2024-02-13 12:26 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const paragraph = document.getElementsByTagName("p");
Done

2024-02-13 12:29 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const alterClass = document.getElementsByClassName("destaque");
Done

2024-02-13 12:30 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const buttonText = document.getElementById("botaoClique");
done

2024-02-13 12:31 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const alterColorList = document.querySelectorAll("li.item");
Done

2024-02-13 12:32 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const alterFontText = document.getElementsByTagName("span")[0];
Done

2024-02-13 12:34 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const elementClass = document.querySelector(".item");
Done

2024-02-13 12:46 UTC, adrianopratesr commented
@antoniomatiolijr meu git ignore nao esta funfando, esta subindo o Ds_Store

2024-02-14 12:45 UTC, antoniomatiolijr requested changes
precisa adicionar no git ignore algo que elimine `.DS_Store`

2024-02-14 12:45 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +for (const alterBackground of highlightedElements) {
const highlightedElement

2024-02-14 12:45 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +for (const alterContent of highlightedElements) {
mesma coisa

2024-02-14 12:45 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const itemElements = document.querySelector(".item");
itemsElements

2024-02-14 18:24 UTC, antoniomatiolijr requested changes

2024-02-14 18:24 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +const highlightedElement = document.getElementsByClassName("destaque");
highlightedElements

2024-02-14 18:24 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +for (const alterBackground of highlightedElement) {
const highlightedElement of highlightedElements

2024-02-14 18:24 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +}
mesma coisa. alterContent é a ação que vc quer que faça eu preciso que vcs prestem atenção nisso. O que precisa ficar gravado na cabeça é que toda variável representa no nome o seu conteúdo guardado. E cada função representa a ação que vai ser realizada, logo alterContent seria o nome de uma função. 

Eu to pegando nesse ponto pq esse conceito é muito importante, não é só questão do nome da variável.

2024-02-14 18:24 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +itemsElements.textContent = "Item Alterado";
e se tiver mais de um?

2024-02-14 18:24 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-7/topico-1/index.js
> +}
listItemElements

2024-02-16 01:42 UTC, antoniomatiolijr approved these changes

2024-02-16 01:42 UTC, merged