Feat/se0 fc1 py modulo1 topico2
adrianopratesr/software-engineering pull request #3
Opened 2023-09-07 04:21 UTC by adrianopratesr

Neste PR estou subindo os exercicios do topico 2

2023-09-28 14:18 UTC, antoniomatiolijr requested changes

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/.vscode/settings.json
> +{
isso tem que estar no seu gitignore e provavelmente vc não abriu o projeto na raiz

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-1.py
> +sumValues = a + b
python usa snake_case ou seja `sum_values`

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-11.py
> +concatString = a + b
snake case

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-12.py
> +a = len("Adriano")
o que é a?

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-13.py
> +a = "Adriano"
o que é a?

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-14..py
> +print(valueA.upper())
meoww

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-14..py
> +print(valueA.upper())
separa em uma variável e só printa o resultado não usa a funçõa direto no print

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-15.py
> +print(a.find("a"))
igual anterior

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-16.py
> +print(type(a))
meow

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-17.py
> +print(a)
meow

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-18.py
> +print(a, b)
meow

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-19.py
> +print(a, b)
meoowwwwww

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-2.py
> +multiplicationValues = a * b
snake_case

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-20.py
> +print(float(a))
tira de dentro do print a conversão

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-21.py
> +print(int(a))
igual anterior

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-22.py
> +print(int(a))
igual anterior

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-23.py
> +print(int(a))
igual anterior

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-24.py
> +print(str(a))
igual anterior

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-25.py
> +print(a)
igual anterior e melhora o nome das variaveis

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-26.py
> +print(a-b)
meow e não faz a operação dentro do print e eu so quero os dias 

difference = b - a
print(difference.days)

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-27.py
> +print(a+b)
faz a operação fora

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-28.py
> +print(a)
meow

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-29.py
> +print(a)
meow

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-3.py
> +divisionValues = a / 5
criou b para que?

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-4.py
> +restValues = 10 % 10
criou as variaveis para que?

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-5.py
> +exponentialValues = a ** b
snake_case

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-6.py
> +sumValuesDecimais = a + b
snake_case

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-7.py
> +divisionValues = a / b
snake case

2023-09-28 14:18 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-9.py
> +compareValues = a > b
snake_case

2023-09-29 12:51 UTC, antoniomatiolijr requested changes

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/.gitignore
> +settings.json
**/settings.json

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/.vscode/settings.json
> +{
ele continua aparecendo rs

Você precisa mover esse arquivo para a raiz do projeto inclusive

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-11.py
> +concatString = a + b
snake case

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-12.py
> +string_name = len("Adriano")
name = "Adriano"
name_length = len(name)

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-13.py
> +value_a = "Adriano"
name

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-14..py
> +value_a = "AdrIaNo"
name

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-15.py
> +find_character = name.find("a")
character

find é uma ação deve ser reservada para métodos e funções

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-2.py
> +multiplication_values = a * b
multiplication_result

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-20.py
> +value_convetion = float(value)
converted_value

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-21.py
> +value_convetion = int(value)
converted_value

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-22.py
> +value_convertion = int(value)
converted_value

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-23.py
> +value_convertion = int(value)
converted_value

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-24.py
> +value_convert = str(value)
converted_value

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-25.py
> +date_format = datetime.now().strftime('%d/%m/%Y %H:%M:%S')
formatted_date

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-26.py
> +date_min = date(2022, 9, 25)
min_date

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-26.py
> +date_max = date(2023, 9, 25)
max_date

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-28.py
> +date_format = datetime.now().strftime('%d de %B de %y')
formatted_date

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-29.py
> +date_format_and_week_days = datetime.now().strftime('%d de %B de %y, the day of the week is: %A')
formatted_date

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-3.py
> +division_values = value_a / value_b
division_result

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-4.py
> +rest_values = value_a % value_b
rest_division_result

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-5.py
> +exponential_values = a ** b
exponential_result

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-6.py
> +sumValues_decimais = a + b
sum_decimals_result

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-6.py
> +sumValues_decimais = a + b
ainda manteve o camelCase errado

2023-09-29 12:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/python/modulo-1/topico-2/exercise-7.py
> +division_values = a / b
result_division

2023-10-01 04:52 UTC, antoniomatiolijr approved these changes

2023-10-01 22:28 UTC, luanarahal approved these changes

2023-10-01 22:28 UTC, merged