Feat/se1 fc1 js modulo 2
adrianopratesr/software-engineering pull request #7
Opened 2023-10-18 15:07 UTC by adrianopratesr

Neste PR estou adicionando os exercicios do Módulo 2 topico 1

2023-10-18 16:39 UTC, antoniomatiolijr requested changes
Nomes de arrays devem ser sempre em plural

2023-10-20 03:40 UTC, antoniomatiolijr requested changes

2023-10-20 03:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-10.js
> +const low_words = words.filter((word) => {
Python? lowWords

2023-10-20 03:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-10.js
> +const low_words = words.filter((word) => {
E não seria bigWords?

2023-10-20 03:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-11.js
> +const sum_values = values.reduce((value, position) => {
Python?

2023-10-20 03:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-11.js
> +});
Cadê o valor inicial?

2023-10-20 03:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-11.js
> +const sum_values = values.reduce((value, position) => {
O primeiro valor é o acumulador um nome melhor é result, amount, accumulator e o segundo não é position e sim o item que está sendo iterado um nome bom é value ou item

2023-10-20 03:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-12.js
> +const salutation_reduce = salutations.reduce((salutation, position) => {
Mesma coisa

2023-10-20 03:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-12.js
> +});
Cadê o valor inicial

2023-10-20 03:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-13.js
> +const find_number = numbers.find((number) => {
Python?

2023-10-20 03:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-14.js
> +const find_character = animals.find((animal) => {
Python?

2023-10-20 03:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-15.js
> +const verify_number_negative = numbers.some((number) => {
hasAnyNegativeNumber

2023-10-20 03:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-16.js
> +const verify_number_negative = numbers.every((number) => {
haveAllPositiveNumbers

2023-10-20 03:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-7.js
> +const double = numbers.map((number) => {
doubledNumbers

2023-10-20 03:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-8.js
> +const upper_case_first = fruits.map((fruit) => {
capitalizedWords

2023-10-20 03:40 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-9.js
> +const odd = numbers.filter((number) => {
oddNumbers

2023-11-11 20:13 UTC, antoniomatiolijr requested changes

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-13.js
> +const findNumber = numbers.find((number) => {
numberLowerThan10

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-14.js
> +const findCharacter = animals.find((animal) => {
animalStartingWithA

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-15.js
> +const verifyNumberNegative = numbers.some((number) => {
verify é um verbo, isso seria nome de função e não de variável o nome aqui certo seria.

hasNegativeNumber?

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-16.js
> +});
thereAreNegativeNumber a diferença do anterior é pq every checa todos

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-18.js
> +const orderFruits = fruits.sort((a, b) => {
orderedFruites

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-19.js
> +const listNames = students.map((student) => {
studentsNames

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-20.js
> +const minorAge = students.filter((ages) => {
studentsInMinorAge

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-21.js
> +const ageEqual = students.find((equal) => {
studentsWith20

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-22.js
> +});
igual anterior e em adição `ages => student`

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-23.js
> +const verifyAge = students.some((ages) => {
igual anterior

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-24.js
> +}, 0);
isso não retorna a média e sim a soma

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-25.js
> +});
olha minha sugestão anterior

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-26.js
> +});
studentsOrderedByName

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-27.js
> +});
igual os anteriores

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-28.js
> +  return student.name + " - " + student.age;
da para usar dessa forma mas eu prefiro template string `${student.name} - ${student.age}`

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-31.js
> +const studentsMoreTwentyYears = students.filter((student) => {
studentsMoreThanTwentyYears

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-32.js
> +console.log(verifyAgesEqual);
arrumar os nomes das variáveis

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-33.js
> +console.log(averageAge);
arrumar as variaveis

2023-11-11 20:13 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-8.js
> +const upperCaseFirst = fruits.map((fruit) => {
fruitsCapitalized

2023-11-12 05:47 UTC, antoniomatiolijr requested changes

2023-11-12 05:47 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-41.js
> +const filterEvents = events.filter((value) => {
filteredEvents

2023-11-12 05:47 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-40.js
> +const ohMyGod = people.map((person) => {
really?

2023-11-12 05:47 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-37.js
> +);
Não é previous é accumulatedAge

2023-11-12 05:47 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-37.js
> +);
pq não é a idade anterior no reduce, e sim o acumulador

2023-11-12 05:47 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-36.js
> +  .filter((a) => a.age > 20)
o que é `a`?

2023-11-12 05:47 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-35.js
> +const alphabeticalOrder = students
variavel mah friend, studentsOrdered

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-11.js
> +});
Fetio

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-12.js
> +});
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-13.js
> +const findNumber = numbers.find((number) => {
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-14.js
> +const findCharacter = animals.find((animal) => {
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-15.js
> +const verifyNumberNegative = numbers.some((number) => {
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-16.js
> +});
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-18.js
> +const orderFruits = fruits.sort((a, b) => {
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-19.js
> +const listNames = students.map((student) => {
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-20.js
> +const minorAge = students.filter((ages) => {
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-21.js
> +const ageEqual = students.find((equal) => {
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-22.js
> +});
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-23.js
> +const verifyAge = students.some((ages) => {
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-24.js
> +}, 0);
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-25.js
> +});
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-26.js
> +});
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-27.js
> +});
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-28.js
> +  return student.name + " - " + student.age;
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-31.js
> +const studentsMoreTwentyYears = students.filter((student) => {
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-9.js
> +const odd = numbers.filter((number) => {
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-8.js
> +const upperCaseFirst = fruits.map((fruit) => {
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-7.js
> +const double = numbers.map((number) => {
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-41.js
> +const filterEvents = events.filter((value) => {
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-40.js
> +const ohMyGod = people.map((person) => {
KKKKKKKKKKKKKKKKKKKKKK um leve humor
#desespelo

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-40.js
> +const ohMyGod = people.map((person) => {
Serei mais tecnico no nome

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-37.js
> +);
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-36.js
> +  .filter((a) => a.age > 20)
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-35.js
> +const alphabeticalOrder = students
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-33.js
> +console.log(averageAge);
Feito

2023-11-12 16:23 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-32.js
> +console.log(verifyAgesEqual);
Feito

2023-11-13 01:33 UTC, antoniomatiolijr requested changes

2023-11-13 01:33 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-12.js
> +}, "");
salutation

2023-11-13 01:33 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-16.js
> +const thereAreNegativeNumber = numbers.every((number) => {
thereAreNegativeNumbers esqueci o s

2023-11-13 01:33 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-18.js
> +const orderedFruites = fruits.sort((a, b) => {
orderedFruits

2023-11-13 01:33 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-23.js
> +  return ages.age > 22;
troca ages por student, não é um array de ages e sim um student

2023-11-13 01:33 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-23.js
> +  return ages.age > 22;
o exercício pede igual a 22

2023-11-13 01:33 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-26.js
> +const filterFirsCharactereA = students.filter((student) => {
studentsWithFirstCharA

2023-11-13 01:33 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-32.js
> +  });
studentsWithSameAge

2023-11-13 01:33 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-29.js
> +}, -Infinity);
jesusss ficou muito complexo, saca.


```javascript
const oldestStudent = students.reduce((oldest, student) => {
    return (oldest.age > student.age) ? oldest : student;
}, {});

```

2023-11-13 01:33 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-34.js
> +});
studentsMoreThan20

2023-11-13 01:33 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-34.js
> +}, Infinity);
mesma coisa do exercício que eu comentei antes

2023-11-13 02:08 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-16.js
> +const thereAreNegativeNumber = numbers.every((number) => {
Feito

2023-11-13 02:08 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-12.js
> +}, "");
Feito

2023-11-13 02:08 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-18.js
> +const orderedFruites = fruits.sort((a, b) => {
Feito

2023-11-13 02:08 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-23.js
> +  return ages.age > 22;
Feito

2023-11-13 02:08 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-26.js
> +const filterFirsCharactereA = students.filter((student) => {
Feito

2023-11-13 02:08 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-29.js
> +}, -Infinity);
opss kkkkkk

2023-11-13 02:08 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-32.js
> +  });
Feito

2023-11-13 02:08 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-34.js
> +});
Feito

2023-11-13 02:08 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-34.js
> +}, Infinity);
Feito

2023-11-13 02:08 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-8.js
> +const upper_case_first = fruits.map((fruit) => {
Feito

2023-11-13 02:09 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-11.js
> +const sum_values = values.reduce((value, position) => {
Feito

2023-11-13 02:10 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-12.js
> +const salutation_reduce = salutations.reduce((salutation, position) => {
Feito

2023-11-13 02:10 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-16.js
> +const verify_number_negative = numbers.every((number) => {
Feito

2023-11-13 02:11 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-12.js
> +}, "");
Feito

2023-11-13 02:38 UTC, antoniomatiolijr requested changes

2023-11-13 02:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-23.js
> +  return student.age > 22;
é igual não maior

2023-11-13 02:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-34.js
> +});
troca oldest nesse caso para youngest

2023-11-13 02:38 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-34.js
> +const minorAge = studentsMoreThan20.reduce((oldest, student) => {
minorAge coloca youngestStudent

2023-11-13 02:39 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-34.js
> +});
Feito

2023-11-13 02:40 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-23.js
> +  return student.age > 22;
Feito

2023-11-13 02:41 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-34.js
> +const minorAge = studentsMoreThan20.reduce((oldest, student) => {
Feito

2023-11-13 02:51 UTC, antoniomatiolijr requested changes

2023-11-13 02:51 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-34.js
> +  return youngest.age < student.age ? oldest : student;
Esqueceu o oldest aqui nem testou safado

2023-11-13 02:55 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-1/ex-34.js
> +  return youngest.age < student.age ? oldest : student;
eu tinha testado com oldest confesso kkkkkkk

2023-11-13 02:59 UTC, antoniomatiolijr approved these changes

2023-11-13 03:05 UTC, luanarahal approved these changes

2023-11-13 03:06 UTC, merged