Feat/se1 fc1 js modulo2 topico2
adrianopratesr/software-engineering pull request #8
Opened 2023-11-30 01:30 UTC by adrianopratesr

este pr adiciona os exercicios do módulo 4

2023-11-30 05:28 UTC, antoniomatiolijr requested changes

2023-11-30 05:28 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-15.js
> +  console.log(chave, valor);
Em inglês

2023-11-30 05:28 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-17.js
> +const mapa2 = new Map([["chave2", "valor2"]]);
Inglês

2023-11-30 05:28 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-18.js
> +const convertInMap = new Map();
newMap

2023-11-30 05:28 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-19.js
> +const mapWords = new Map();
wordsMap

2023-11-30 05:28 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-19.js
> +words.forEach((chave) => {
key

2023-11-30 05:28 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-28.js
> +object.add({ oi: "tchau" });
Coloque objetos que fazem sentido algo como name e o nome

2023-11-30 05:28 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-5.js
> +for (let properties in book) {
const

2023-11-30 05:28 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-9.js
> +});
Da pra trocar por forEach

2023-12-03 09:36 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-15.js
> +  console.log(chave, valor);
Feito

2023-12-03 09:36 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-17.js
> +const mapa2 = new Map([["chave2", "valor2"]]);
feito

2023-12-03 09:36 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-18.js
> +const convertInMap = new Map();
Feito

2023-12-03 09:36 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-19.js
> +const mapWords = new Map();
Feito

2023-12-03 09:36 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-19.js
> +words.forEach((chave) => {
feito

2023-12-03 09:36 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-28.js
> +object.add({ oi: "tchau" });
Feito

2023-12-03 09:36 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-5.js
> +for (let properties in book) {
Feito

2023-12-03 09:36 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-9.js
> +});
feito

2023-12-03 18:42 UTC, antoniomatiolijr requested changes

2023-12-03 18:42 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-28.js
> +object.add({ cat: "roberto" });
A estrutura tá estranha desse objeto coloca algo representativo

2023-12-03 19:15 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-28.js
> +object.add({ cat: "roberto" });
Mano eu alterei o nome na estrutura, pois o exercicio pede 3 objetos diferentes

2023-12-04 00:56 UTC, antoniomatiolijr requested changes

2023-12-04 00:56 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-28.js
> +object.add({ catName: "roberto" });
name:

2023-12-04 00:56 UTC, antoniomatiolijr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-28.js
> +object.add({ dogName: "sol" });
name

2023-12-04 03:14 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-28.js
> +object.add({ catName: "roberto" });
Feito

2023-12-04 03:14 UTC, adrianopratesr commented on associate-software-engineer/fc-1/javascript/modulo-2/topico-2/ex-28.js
> +object.add({ dogName: "sol" });
Feito

2023-12-04 13:36 UTC, antoniomatiolijr approved these changes

2023-12-04 13:37 UTC, merged